name: first_flutter_project
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flame: ^1.8.2
  flame_audio: ^2.0.5
  hive: 2.2.3
  path_provider: ^2.1.1
  provider: ^6.0.5
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  hive_generator: 2.0.1
  build_runner: 2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/background/
    - assets/images/skeleton_stripes/
    - assets/images/enemy_stripes/
    - assets/images/other/
  fonts:
    - family: Audiowide
      fonts:
        - asset: assets/fonts/Audiowide/Audiowide-Regular.ttf
    - family: BlackShepherd
      fonts:
        - asset: assets/fonts/shepherd/Black-Shepherd.otf
